#!/usr/bin/env bash
# Install and configure nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
service nginx start

echo "hello world" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page ordinaire" | sudo tee /var/www/html/404.html

printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        error_page 404 /404.html;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
                return 301 https://www.google.com;
        }

        location /404 {
                root /var/www/html/;
                internal;
        }

}" > /etc/nginx/sites-available/default

service nginx restart
service nginx reload
