#!/usr/bin/env bash
# This script print Best School 10 times and say hi on the 9 line
i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    (( i++ ))
done
