#!/usr/bin/env bash
# This script prints Best School 10 times, good luck for the 8th and bad luck for the 4th
i=1
while [ $i -le 10 ]
do
    if [ "$i" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++ ))
done
