#!/usr/bin/env bash
# This script print the print until 12:59
min=1
hour=1
realmin=$((min%60))
while [ $hour -le 13 ]
do
	if [ $realmin -eq 0 ]
	then
		if [ $hour -ne 13 ]
		then
			echo "Hour: $hour"
		fi
		((hour++ ))
	else
		echo $realmin
	fi
	((min++ ))
	realmin=$((min%60))
done
