#!/usr/bin/env bash
# Change home IP
cp /etc/hosts ~/hosts.new
sed -i '/localhost$/c\127.0.0.2\tlocalhost' ~/hosts.new
if grep -q 'facebook.com$' ~/hosts.new; then
	sed -i '/facebook.com$/c\8.8.8.8\tfacebook.com' ~/hosts.new
else
	echo "8.8.8.8	facebook.com" >> ~/hosts.new
fi
cat ~/hosts.new > /etc/hosts
